## Makefile (repo-owned) -- generated by `uvx rhiza-task shim > Makefile`
#
# A compatibility shim, not the documented interface -- that is `uv run rhiza-task <task>`.
# It exists for workflows pinned at @v1.3.3 and earlier that still call `make test`, and
# for repos with no Python project to hold the pin. Bumping RHIZA_TASK is the migration.
#
# Repo-specific *tasks* go in a `rhiza_task.tasks` entry point, repo-specific *targets* in
# `local.mk` -- or below the shim, if they must be committed: `local.mk` is gitignored.
RHIZA_TASK ?= rhiza-task@0.3.1

# uv cannot be delegated, because uv is what runs the CLI. Prepended so a machine carrying
# an older uv still resolves the pin, exported because task bodies shell out to bare `uv`.
INSTALL_DIR ?= $(abspath ./bin)
UVX ?= $(shell command -v uvx 2>/dev/null || echo $(INSTALL_DIR)/uvx)
export PATH := $(INSTALL_DIR):$(PATH)

# `UV` too, for `local.mk` to reach: the astral installer writes both binaries into the
# same directory, so once $(UVX) exists this does, and the empty recipe both satisfies
# make's remake attempt and keeps the catch-all from forwarding the path as a task name.
UV ?= $(shell command -v uv 2>/dev/null || echo $(INSTALL_DIR)/uv)
$(UV): $(UVX) ;

.DEFAULT_GOAL := help

.PHONY: help

# `rhiza-task list` cannot know about the targets `local.mk` adds, so anything there with
# a `##` comment is listed under them. This is what lets a repo move its own targets out
# of this file without losing them from `make help`.
help: $(UVX)
	@$(UVX) $(RHIZA_TASK) list
	@own=$$(grep -hE '^[a-zA-Z0-9_-]+:.*##' $(MAKEFILE_LIST) | sed -e 's/:.*##/ -- /' -e 's/^/  /'); \
		[ -z "$$own" ] || printf '\nRepo-owned targets:\n%s\n' "$$own"

# Every task, and every typo -- the CLI's "unknown task" error is the backstop. `FORCE` is
# what keeps them phony: .PHONY takes no patterns, but a phony prerequisite is never up to
# date, so `make book` next to a `book/` directory still runs. Recursive `=` because `$@`
# only has a value while make is running the rule.
RHIZA_TASK_GOAL = $@

%: $(UVX) FORCE
	@$(UVX) $(RHIZA_TASK) $(RHIZA_TASK_GOAL)

# A file target, so make's up-to-date check is the idempotence. `$(UVX)` and not
# `$(INSTALL_DIR)/uvx`, because an on-PATH uvx would otherwise be matched by the catch-all
# whose prerequisite is that same file: `make: Circular ... dependency dropped`.
$(UVX):
	@echo "[INFO] uv not found; installing into $(@D)"
	@curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR="$(@D)" sh >/dev/null

.PHONY: FORCE
FORCE:

# Repo-specific one-offs. An explicit rule beats a pattern rule, so these win.
-include local.mk

# Both are targets make tries to remake, and the catch-all would route that to the CLI.
local.mk: ;
Makefile: ;
