## Makefile (repo-owned) -- generated by `uvx rhiza-task shim > Makefile`
#
# Not the documented interface. That is `uv run rhiza-task <task>`: the same string CI
# runs, with the version pinned in pyproject.toml and uv.lock, so a disagreement between
# two checkouts surfaces as a lockfile diff rather than as a gate that quietly behaved
# differently. Two paths to the same gate can diverge; one cannot.
#
# This file is for the two cases that cannot say that:
#
#   1. Reusable workflows pinned at @v1.3.3 and earlier call `make test`, `typecheck`,
#      `deps`, `fmt`, `docs-coverage`, `security`, `license`, `rhiza-test`. Those pins keep
#      calling make forever, so make keeps answering. Task names match the retired target
#      names for exactly this reason.
#   2. Repositories with no Python project. A crate or a Go module has no dev group to hold
#      the pin and nothing for `uv run` to run in, so RHIZA_TASK below is the only copy of
#      the version and this file is the only place it can live.
#
# So: a compatibility shim, and a home for the pin. It forwards to the CLI and holds no
# logic -- bumping RHIZA_TASK is the whole migration.
RHIZA_TASK ?= rhiza-task@0.3.1

# uv is the one thing that cannot be delegated, because uv is what runs the CLI. The case
# is a cold clone on a machine without uv -- the interactive path this file now owns, since
# CI provisions uv with `astral-sh/setup-uv` and invokes the CLI directly. Prepended so a
# machine carrying an older uv still resolves the pin above, and exported because every
# task body shells out to a bare `uv`/`uvx`.
INSTALL_DIR ?= $(abspath ./bin)
UVX ?= $(shell command -v uvx 2>/dev/null || echo $(INSTALL_DIR)/uvx)
export PATH := $(INSTALL_DIR):$(PATH)

.DEFAULT_GOAL := help

# `help` is the one named target, because `make` with no argument has to land somewhere.
# The rest are deliberately not spelled out: the catch-all below already forwards them, so
# a named list here is a hand-maintained mirror of one the CLI owns and prints, costing a
# commit every time a task is added, renamed or dropped. `rhiza-task list` is the
# discoverable surface; `FORCE` below, not a list, is what keeps the tasks phony.
.PHONY: help

help: $(UVX)
	@$(UVX) $(RHIZA_TASK) list

# Every task the CLI offers comes through here, and so does a typo -- the CLI's "unknown
# task" error is the backstop. `RHIZA_TASK_GOAL` is `$@` named; recursive `=` because `$@`
# only has a value while make is running the rule.
#
# `FORCE` is what makes each forwarded task phony. A match-anything rule is still subject
# to make's up-to-date check, so next to a `book/` directory `make book` is "`book' is up
# to date" and the recipe never runs -- the reason the named targets used to be spelled out
# and declared .PHONY. .PHONY takes no patterns, but a prerequisite that is itself phony is
# never up to date, so the recipe always runs. It covers every target the CLI has rather
# than the ones a list happened to name, and needs no upkeep when that set changes.
RHIZA_TASK_GOAL = $@

%: $(UVX) FORCE
	@$(UVX) $(RHIZA_TASK) $(RHIZA_TASK_GOAL)

# A file target, so make's own up-to-date check is the idempotence: no probe to get wrong,
# no second invocation that re-downloads. The target is `$(UVX)` and not
# `$(INSTALL_DIR)/uvx` because an on-PATH uvx with no rule of its own is matched by the
# catch-all, whose prerequisite is that same file: `make: Circular ... dependency dropped`.
# `$(@D)` so an overridden `UVX=/somewhere/uvx` provisions /somewhere.
$(UVX):
	@echo "[INFO] uv not found; installing into $(@D)"
	@curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR="$(@D)" sh >/dev/null

# An explicit rule beats a pattern rule, so `FORCE` is not routed to the CLI by the
# catch-all, and an empty recipe is all it needs.
.PHONY: FORCE
FORCE:

# Repo-specific one-offs, and what `.rhiza/make.d/` fragments must move into. An explicit
# rule beats a pattern rule, so these win over the catch-all.
-include local.mk

# An included makefile is also a target make tries to remake, and with a match-anything
# rule in scope that attempt is routed to the CLI -- so every invocation used to open with
# "unknown task: local.mk". The Makefile needs the same: `$(UVX)` is a prerequisite a cold
# checkout creates, making the Makefile out of date, so make ran `uvx rhiza-task Makefile`
# and died right after installing uv. Empty recipes end both.
local.mk: ;
Makefile: ;
